### ISSUE TITLE
Unable to launch Cappy twice in Noclip mode

### ISSUE THREAD

**Issue by Fuzzy2319** [Amethyst-szs/smo-lunakit#13]
Step to reproduce:

- Enable Noclip
- Press X or Y
- Press X or Y again

See below:

https://user-images.githubusercontent.com/61144247/226640424-b8415941-ae92-40f3-9d5d-6db4751fe3bd.mp4

**Comment by Amethyst-szs** [comment]
This is the same bug as your last issue report, just with a slightly effect
