### ISSUE TITLE
Athmosphere Fatal Error with LunaKit

### ISSUE THREAD

**Issue by ThatsNoelle** [Amethyst-szs/smo-lunakit#15]
Hii !
I have a problem when I launch Super Mario Odyssey with the LunaKit Mod on my switch, it crashes my Switch with the following error message :
"Panic occurred while running Athmosphere.

Title ID : 010000000000000D (a.k.a celui de SMO)
Error: std: abort (0xFFE)"

My SMO is in 1.0.0 (well I guess) using the odyssey downgrade homebrew and idk how to fix this issue..?

I can't put the error log because GitHub don't support .bin files, so here is a link to download it if you want to analyse it... : https://we.tl/t-Ldinjo1kDa

Thx for the possible help !

(btw sorry if my english is not perfect, i'm a french student and i'm not very good in english language...)

**Comment by Amethyst-szs** [comment]
Unfortunately there is very little I can do to find the source of an atmosphere fatal crash. Unless you can supply some more information about exactly when and where it crashed, I'll have to make the assumption this is something on your end

**Comment by ThatsNoelle** [comment]
The crash appens when I launch SMO with the mod active (with and without SimpleModManager). There isn't any loading logo and even not the Nintendo Switch Logo.

Here is a link to have 2 videos, one without LunaKit, and another with LunaKit (and also the crash of course) : https://we.tl/t-FOvcddBpMn

The fact that it is on my end is not impossible, but seems strange for me...

**Comment by Amethyst-szs** [comment]
Mod isn't designed for simple mod manager, and it doesn't sound like something coming from the mod itself. Re-follow the install instructions and do some outside troubleshooting
