### ISSUE TITLE
[BUG] The tcp server doth not worketh

### ISSUE THREAD

**Issue by Crazalu** [Amethyst-szs/smo-lunakit#27]
**Describe the bug**
When I put in my ip it not work (port 3080 also didnt work but changed it to see if it was the problem

no clue how to reproduce issue (for you at least for me it just doesn't work)

![image](https://user-images.githubusercontent.com/118357378/234425334-70d4ed36-1e1b-4ade-8745-80d76eb35dc7.png)

Nintendo Switch

**Comment by Amethyst-szs** [comment]
Looks like an issue with your router/input, unless you have a port forwarding setup, make sure you're using local IP addresses

**Comment by MonsterDruide1** [comment]
Can confirm that it works just fine. You can get the local address on Windows machines using `ipconfig`, then look for the one that says `Ethernet adapter` (probably has the most options listed below as well). There, take the `IPv4-Address` - most likely it will start with `192.168.0`, but can also be something quite different.
