### ISSUE TITLE
[BUG] The TCP Server throws an error and stops working

### ISSUE THREAD

**Issue by GabCoolDude** [Amethyst-szs/smo-lunakit#30]
**Describe the bug**
The tcp server attempts to connect and immediatly throws OSError: [Errno 99] Cannot assign requested address

**To Reproduce**
1. Run tcpServer.py
2. Wait for the error

**Screenshots**
![hello-there](https://user-images.githubusercontent.com/123309403/234636082-360568d6-0212-4249-85a3-bd3b42f57a07.jpeg)

**Platform**
Obviously trying to make this work with a nintendo switch.
The tcpServer.py is on a linux ubuntu machine

**Comment by CoolFrenchPerson** [comment]
Woops , i forgot to add a title
Hope that's okay

**Comment by MonsterDruide1** [comment]
Same as #27 
Make sure to use your local IP address. You can get the local address on Linux machines using `ifconfig`, then look for the one that says `eth0`. There, take the `inet` - most likely it will start with `192.168.0`, but can also be something quite different.

**Comment by GabCoolDude** [comment]
Oh, sorry i thought we had to use the switch's ip for some reason, my bad !
