### ISSUE TITLE
[BUG]The ip and port of the tcp Server does not get remembered

### ISSUE THREAD

**Issue by GabCoolDude** [Amethyst-szs/smo-lunakit#32]
**Describe the bug**
Thy lunakit does not want to log the ip and port i enter for server logging

**To Reproduce**
1. Go to Extras
2. Enter Ip and port in Server Logging
3. Relaunch the game

**Screenshots**
Here you can see i entered the ip and port
![image](https://user-images.githubusercontent.com/123309403/235367779-3c5f995c-0ab3-4520-8809-8c753c9d78c8.png)
And on the next boot of the game, it has disappeared
![Screenshot from 2023-04-30 19-29-07](https://user-images.githubusercontent.com/123309403/235367827-d31c7b63-2ab7-4441-94a2-9c95027740fc.png)

**Platform**
I am on Nintendo Switch, and the tcp server is on linux ubuntu

**What I've tried**
I have tried saving in the game's ui
I have tried saving in lunakit's ui
And i have tried autosaves triggered by the mods being enabled in lunakit's ui ( infinite cap bounce for exemple )

**Comment by Amethyst-szs** [comment]
Small issue, you need to click the "Activate Logger" button ahaha

In a future update I'll make the button stand out more so this isn't an issue anybody runs into in the future

**Comment by GabCoolDude** [comment]
Thank you, that seems to have done the trick !
