### ISSUE TITLE
[BUG] When clicking on something in the actor editor, the mouse starts lagging in ryujinx

### ISSUE THREAD

**Issue by ghost** [Amethyst-szs/smo-lunakit#39]
When clicking on anything in the actor editor, my mouse pointer starts to lag

**Comment by Amethyst-szs** [comment]
This is an issue with Ryujinx itself, I've reached out to them about this to no avail unfortunately. As a temporary fix, go to the "Extras" tab and disable scrolling. This will fix the lag but will sadly remove scroll wheel functionality, requiring you to use the bar on the side

**Comment by ghost** [comment]
Thanks
