### ISSUE TITLE
Enabling ActorBrowser crashes the game

### ISSUE THREAD

**Issue by MonsterDruide1** [Amethyst-szs/smo-lunakit#6]
Setup (first encounter):
- Open a save file currently located in Bowser's Kingdom
- Enable ActorBrowser in the menu bar using the controller inputs

Crash report:
[01679162966_0100000000010000.log](https://github.com/Amethyst-szs/smo-lunakit/files/11009256/01679162966_0100000000010000.log)

Screenshot:
![01679162966_0100000000010000](https://user-images.githubusercontent.com/26349348/226126214-73572ab1-a7dd-426a-b7f2-489a9615edf3.jpg)

**Comment by Amethyst-szs** [comment]
Do you happen to have any other mods installed by chance? I have a feeling it might be messing up cause of custom actors?

**Comment by MonsterDruide1** [comment]
There are no other active mods, except for the Downgrade... do you think that one causes problems?

**Comment by MonsterDruide1** [comment]
Also crashes at the same action when running in Yuzu, although I can't look at the backlog there.

**Comment by Amethyst-szs** [comment]
Well that makes sense, the only emulator I've gotten confirmation of working is Ryujinx, I'll do some digging into the crash report and see if I can figure out anything

**Comment by MonsterDruide1** [comment]
Answering here from the Modding Hub: Yes, using that modified `exefs` fixes the crash both on console and Yuzu for me!

**Comment by Amethyst-szs** [comment]
Awesome! Committing to the dev branch now, will be on the stable build soon!

**Comment by Crazalu** [comment]
can confirm yuzu works
