### ISSUE TITLE
Interface doesn't open when using attached joycons in portable mode

### ISSUE THREAD

**Issue by ibelieveinwhatileaveinthewaybehind** [Amethyst-szs/smo-lunakit#7]
Holding ZR + R, then tapping L does not open LunaKit's interface when using a switch in portable mode (with joycons attached to the switch)

**Comment by MonsterDruide1** [comment]
Can confirm this - when in handheld mode, no button inputs are getting picked up by LunaKit. When enabling controller inputs before, it's not possible to disable them anymore, use the menu or actually control the game - essentially blocking all input until controllers are disconnected from the console again.

**Comment by Amethyst-szs** [comment]
Replicated the issue on my end and tracked down the source of the problem. Looks like ExLaunch's InputHelper library doesn't detect attached joy-con as controllers (for some reason)

Will be looking into fixing this asap!

**Comment by Amethyst-szs** [comment]
Fixed! This was an absolute headache (turns out handheld mode controls are stored on port 32), fix is already on the dev branch and will be pulled up to stable on a bugfix release soon
